version: "3.8"

services:
  db:
    image: postgres:16.1-bullseye
    restart: always
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=wb_orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: