FROM golang:alpine AS builder

WORKDIR /build
ADD go.mod .
COPY . .
RUN go build -o server ./cmd/sub/server.go

FROM alpine

WORKDIR /build
COPY --from=builder /build/server /build/server
COPY /static /build/static
RUN chmod +x server
CMD ["/build/server"]